#!/bin/bash

# calculate battery percentage 
current_charge=`cat /sys/class/power_supply/BAT0/charge_now`
max_charge=`cat /sys/class/power_supply/BAT0/charge_full`
charge_perc=`echo "($current_charge/$max_charge)*100" | wcalc -P0`

if [ ${charge_perc:3} -gt 100 ]; then
  echo "100%"
else
  echo -e "${charge_perc:3}%"
fi
#echo -e "$charge_perc%"
